### PR TITLE
Update to storage equations

### PR DESCRIPTION
**Pull request by Mattia-Allione**
Hi, in this branch I uploaded my code where I added to the pyomo code the storage equations, storage constraints and storage investments and fixed a bug related to the constraint capacity of one tehnology unit.
Cheers,
Mattia

### CODE REVIEW

**Comment by willu47** [comment]
Hi @Mattia-Allione - thanks for this. In order to merge in this pull request, ideally you should overwrite the original Pyomo file with the changes you have made. We will then be able to see the difference between your code, and those in the original Pyomo implementation of OSeMOSYS. Also, given the decision in OSeMOSYS/OSeMOSYS#98, that these changes would be better as an "optional extra", I would prefer if your implementation lives in a branch in this repository, rather than in an extra file on the master branch.

**Comment by Mattia-Allione** [comment]
Hi, I now have overwritten the original pyomo file. I am not sure why it should be an optional extra since I have not made changes in the code and I just "translated" storage equation to pyomo from this code: https://github.com/OSeMOSYS/OSeMOSYS_GNU_MathProg/blob/5daea546643298be9d84b0108e4c2dd8e228ee7b/src/osemosys.txt .
Anyway if needed I will branch it into an "optional extra"

**Comment by willu47** [comment]
Hi @Mattia-Allione - apologies. I am getting confused. So this pull request relates to issue #1  in which you have updated the storage equations?

Okay, I will edit the title of the pull request so that it is clear what you are suggesting to merge into the main versoin of OSeMOSYS Pyomo.

**Comment by tniet** [comment]
Hi @willu47 @Mattia-Allione - I think the question that comes up for me at this point is who is taking the lead on the Pyomo version of OSeMOSYS?  I don't have any expertise in Pyomo specifically and don't have time to review any Pyomo additions so can't really review this pull request in any detail.  Not sure if @abhishek0208 or @willu47 have that expertise or are wanting to review Pyomo code...

**Comment by Mattia-Allione** [comment]
Hi @willu47, yes it is, sorry if my title was not clear. Thanks for changing the title

**Pull request merged**
