### PR TITLE
Addition of RE production target constraints

### LINKED ISSUE #8: Missing RE Production Target constraints
@ThomasHeggarty that, along with the storage constraints (see #1 and #2 ), the pyomo code is also missing the "RE Production Target constraints", despite being in the official OSeMOSYS problem description. I do not know if this is deliberate; @ThomasHeggarty has written the associated pyomo code and can upload it if need be.

### PR DESCRIPTION
**Pull request by ThomasHeggarty**
As agreed. Closes #8

### CODE REVIEW

**Comment by willu47** [comment]
I've added a simple test which runs the model using the included UTOPIA model.  I notice that these changes have caused the test to fail with the following error:
```python
$ pyomo solve --solver=glpk osemosys.py UTOPIA_2015_08_27.dat
[    0.00] Setting up Pyomo environment
[    0.00] Applying Pyomo preprocessing actions
[    0.34] Creating model
ERROR: Rule failed when generating expression for constraint
    FuelProductionByTechnologyAnnual with index ('UTOPIA', 'E01', 'CSV',
    1990): KeyError: "Index '('UTOPIA', 'E01', 'CSV', 1990, 'ID')' is not
    valid for indexed component 'ProductionByTechnology'"
ERROR: Constructing component 'FuelProductionByTechnologyAnnual' from
    data=None failed:
        KeyError: "Index '('UTOPIA', 'E01', 'CSV', 1990, 'ID')' is not valid
        for indexed component 'ProductionByTechnology'"
[    9.55] Pyomo Finished
ERROR: Unexpected exception while running model:
        Index '('UTOPIA', 'E01', 'CSV', 1990, 'ID')' is not valid for indexed
        component 'ProductionByTechnology'
The command "pyomo solve --solver=glpk osemosys.py UTOPIA_2015_08_27.dat" exited with 1.
```

**Comment by ThomasHeggarty** [comment]
Sorry about this, it is due to an inconsistency in the order in which sets appear in constraint definitions. Here is the correction.

**Comment by ThomasHeggarty** [comment]
[OSeMOSYS_11_06_20.py.txt](https://github.com/OSeMOSYS/OSeMOSYS_Pyomo/files/4763976/OSeMOSYS_11_06_20.py.txt)

**Comment by willu47** [comment]
@ThomasHeggarty - if you just make another commit on this same branch, you're changes will update the pull request.

**Comment by ThomasHeggarty** [comment]
@willu47 - Sorry, still trying to get my head around github.

**Pull request merged**
